import { type RouteConfig, route, layout, index } from "@react-router/dev/routes";

export default [
  layout("../src/layouts/MainLayout/MainLayout.tsx", [
    index("../src/pages/Home/Home.tsx"),
    route("about", "../src/pages/Company/About.tsx"),
    route("about/mission", "../src/pages/Company/Mission.tsx"),
    route("about/leadership", "../src/pages/Company/Leadership.tsx"),
    route("about/global-footprint", "../src/pages/Company/GlobalFootprint.tsx"),
    route("about/global", "../src/pages/Company/GlobalFootprint.tsx", { id: "about-global" }),
    route("blog", "../src/pages/Company/BlogListing.tsx"),
    route("blog/:slug", "../src/pages/Company/BlogDetail.tsx"),
    route("contact", "../src/pages/Company/Contact.tsx"),
    route("partners", "../src/pages/Company/Partners.tsx"),
    route("privacy-policy", "../src/pages/Legal/PrivacyPolicy.tsx"),
    route("cookies-policy", "../src/pages/Legal/CookiesPolicy.tsx"),
  ]),
  layout("../src/layouts/ServicesLayout/ServicesLayout.tsx", [
    route("services/custom-software-development", "../src/pages/ServicesPages/CustomSoftwareDevelopment.tsx"),
    route("services/mobile-app-development", "../src/pages/ServicesPages/MobileAppDevelopment.tsx"),
    route("services/web-app-development", "../src/pages/ServicesPages/WebAppDevelopment.tsx"),
    route("services/app-reengineering", "../src/pages/ServicesPages/AppReengineering.tsx"),
    route("services/quality-assurance", "../src/pages/ServicesPages/QualityAssurance.tsx"),
    route("services/salesforce", "../src/pages/ServicesPages/Salesforce.tsx"),
    route("services/shopify", "../src/pages/ServicesPages/Shopify.tsx"),
    route("services/service-now", "../src/pages/ServicesPages/ServiceNow.tsx"),
    route("services/data-science-ai", "../src/pages/ServicesPages/DataScienceAI.tsx"),
    route("services/cyber-security", "../src/pages/ServicesPages/CyberSecurity.tsx"),
    route("services/business-process-outsourcing", "../src/pages/ServicesPages/BusinessProcessOutsourcing.tsx"),
    route("services/data-governance", "../src/pages/ServicesPages/DataGovernance.tsx"),
    route("services/dedicated-teams", "../src/pages/ServicesPages/DedicatedTeams.tsx"),
    route("services/cloud-engineering", "../src/pages/ServicesPages/CloudEngineering.tsx"),
    route("services/cloud-migration", "../src/pages/ServicesPages/CloudMigration.tsx"),
    route("services/devops", "../src/pages/ServicesPages/DevOps.tsx"),
    route("services/aws", "../src/pages/ServicesPages/AWS.tsx"),
    route("services/azure", "../src/pages/ServicesPages/Azure.tsx"),
    route("services/digital-evolution", "../src/pages/ServicesPages/DigitalEvolution.tsx"),
    route("services/fixed-price", "../src/pages/ServicesPages/FixedPrice.tsx"),
    route("services/ideation-workshop", "../src/pages/ServicesPages/IdeationWorkshop.tsx"),
    route("services/product-development-strategy", "../src/pages/ServicesPages/ProductDevelopmentStrategy.tsx"),
    route("services/proof-of-concept-development", "../src/pages/ServicesPages/ProofOfConceptDevelopment.tsx"),
    route("services/sales-execution-ae", "../src/pages/ServicesPages/SalesExecutionAE.tsx"),
    route("services/outbound-demand-gen", "../src/pages/ServicesPages/OutboundDemandGen.tsx"),
    route("services/paid-media-performance", "../src/pages/ServicesPages/PaidMediaPerformance.tsx"),
    route("services/inbound-organic-growth", "../src/pages/ServicesPages/InboundOrganicGrowth.tsx"),
    route("services/revenue-operations-systems", "../src/pages/ServicesPages/RevenueOperationsSystems.tsx"),
  ]),
  layout("../src/layouts/IndustriesLayout/IndustriesLayout.tsx", [
    route("industries/finance", "../src/pages/IndustriesPages/Finance.tsx"),
    route("industries/automotive", "../src/pages/IndustriesPages/Automotive.tsx"),
    route("industries/compliance", "../src/pages/IndustriesPages/Compliance.tsx"),
    route("industries/startups", "../src/pages/IndustriesPages/Startups.tsx"),
    route("industries/healthcare", "../src/pages/IndustriesPages/Healthcare.tsx"),
    route("industries/mid-sized-businesses", "../src/pages/IndustriesPages/MidSizedBusinesses.tsx"),
    route("industries/wholesale-retail", "../src/pages/IndustriesPages/WholesaleRetail.tsx"),
    route("industries/edtech", "../src/pages/IndustriesPages/Education.tsx"),
    route("industries/construction", "../src/pages/IndustriesPages/Construction.tsx"),
    route("industries/entertainment", "../src/pages/IndustriesPages/Entertainment.tsx"),
    route("industries/real-estate", "../src/pages/IndustriesPages/RealEstate.tsx"),
    route("industries/transportation", "../src/pages/IndustriesPages/Transportation.tsx"),
    route("industries/energy", "../src/pages/IndustriesPages/Energy.tsx"),
    // Aliases for alternate industry URLs to guarantee they always open the real pages
    route("industries/fintech", "../src/pages/IndustriesPages/Finance.tsx", { id: "industries-fintech" }),
    route("industries/ecommerce", "../src/pages/IndustriesPages/WholesaleRetail.tsx", { id: "industries-ecommerce" }),
    route("industries/realestate", "../src/pages/IndustriesPages/RealEstate.tsx", { id: "industries-realestate" }),
    route("industries/fashiontech", "../src/pages/IndustriesPages/WholesaleRetail.tsx", { id: "industries-fashiontech" }),
  ]),
  route("projects", "../src/pages/Company/Projects.tsx"),
  route("projects/:id", "../src/pages/Company/ProjectDetails.tsx"),
  route("studio/*", "../src/pages/Studio/StudioPage.tsx"),
  route("*", "../src/pages/ErrorPage/Error.tsx"),
] satisfies RouteConfig;
